# Generated by Django 2.0 on 2018-06-14 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_verifycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='verification code'),
        ),
    ]
