# Generated by Django 2.0 on 2018-06-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_auto_20180614_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
